# backend/main.py
from typing import List, Optional
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()


class FileInfo(BaseModel):
    filename: str
    status: Optional[str] = None
    additions: Optional[int] = None
    deletions: Optional[int] = None
    changes: Optional[int] = None
    patch: Optional[str] = None  # unified diff string
    base_content: Optional[str] = None  # full file content before change
    head_content: Optional[str] = None  # full file content after change


class ReviewPayload(BaseModel):
    kind: str  # "review" or "review_comment"

    # review-level fields
    review_body: Optional[str] = None
    review_state: Optional[str] = None

    # inline-comment-level fields
    comment_body: Optional[str] = None
    comment_path: Optional[str] = None
    comment_diff_hunk: Optional[str] = None
    comment_position: Optional[int] = None
    comment_id: Optional[int] = None

    reviewer_login: Optional[str] = None
    pr_number: int
    pr_title: Optional[str] = None
    pr_body: Optional[str] = None
    pr_author_login: Optional[str] = None
    repo_full_name: str
    repo_owner: Optional[str] = None
    repo_name: Optional[str] = None

    files: Optional[List[FileInfo]] = None


class BackendResponse(BaseModel):
    comment: str


@app.post("/analyze-review", response_model=BackendResponse)
async def analyze_review(payload: ReviewPayload):
    # Debug: print full JSON payload to server stderr
    import json, sys

    print("==== Incoming payload ====", file=sys.stderr)
    print(json.dumps(payload.dict(), indent=2), file=sys.stderr)
    print("==========================", file=sys.stderr)

    files = payload.files or []
    num_files = len(files)

    # figure out where the text came from
    if payload.kind == "review":
        source_desc = f"full review (**{payload.review_state}**)"
        text = payload.review_body or ""
    else:
        source_desc = (
            f"inline comment on `{payload.comment_path}` "
            f"(position {payload.comment_position})"
        )
        text = payload.comment_body or ""

    header = (
        f"I received a **{payload.kind}** ({source_desc}) on PR "
        f"**#{payload.pr_number} – {payload.pr_title}** in `{payload.repo_full_name}`.\n\n"
        f"**Reviewer:** `{payload.reviewer_login}`\n\n"
        f"**Original text:**\n\n> {text.replace('\n', '\n> ')}\n\n"
        f"I see **{num_files} changed file(s)**.\n\n"
    )

    snippet = ""

    if num_files > 0:
        f = files[0]
        before_full = (f.base_content or "").splitlines()
        after_full = (f.head_content or "").splitlines()

        snippet += f"### Debug – first changed file: `{f.filename}`\n\n"
        snippet += (
            f"- Status: `{f.status}`\n"
            f"- Before total lines: **{len(before_full)}**\n"
            f"- After total lines: **{len(after_full)}**\n\n"
        )

        # Show first few lines of *full* contents, not just the diff
        snippet += "**First lines BEFORE (full file):**\n```text\n"
        for line in before_full[:15]:
            snippet += line + "\n"
        snippet += "```\n\n"

        snippet += "**First lines AFTER (full file):**\n```text\n"
        for line in after_full[:15]:
            snippet += line + "\n"
        snippet += "```\n\n"

    footer = "_(auto-generated by ContextWizard backend – debug mode: showing full before/after file contents)_"

    return BackendResponse(comment=header + snippet + footer)
